# Site Settings
title: Martin Polacek
email: martinpolacek@stonybrook.edu
description: >
  Martin Polacek personal webpage and blog.
baseurl: ""
url: "http://localhost:4000"
twitter_username: martin_polacek
github_username:  KvitnucaZahradka
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
